# 阶段 1: 构建
FROM maven:3.9-eclipse-temurin-25-alpine AS builder
WORKDIR /app
COPY pom.xml .
COPY settings.xml /tmp/settings.xml
COPY src ./src
# 使用 JDK 25 编译
#RUN mvn clean package -DskipTests -Dmaven.compiler.release=25
# Dockerfile
RUN --mount=type=cache,target=/root/.m2 \
    mvn -s /tmp/settings.xml clean package -DskipTests -Dmaven.compiler.release=25


# 阶段 2: 运行
FROM eclipse-temurin:25-jre-alpine
WORKDIR /app

# 安装 curl 用于健康检查
RUN apk add --no-cache curl

COPY --from=builder /app/target/*.jar app.jar

# 显式开启虚拟线程 (虽然 SB 4.0 默认开启，但显式声明更稳妥)
ENV JAVA_TOOL_OPTIONS="-XX:+EnableDynamicAgentLoading -Xms512m -Xmx1g"

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "app.jar"]